version: '3'

services:
  website:
    build: .
    ports:
      - '3000:3000'
      - '4567:4567'
    volumes:
      - ./:/usr/src/app
      # Avoid mapping host's node_modules
      - /usr/src/app/node_modules
    links:
      - mongodb
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/gtaonlinejobs

  mongodb:
    image: mongo
    restart: always
    expose:
      - '27017'
    volumes:
      - db-data:/data/db

  redis:
    image: redis
    restart: always
    expose:
      - '6379'
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
