version: '3'

services:
  website:
    build: .
    volumes:
      - './:/usr/src/app'
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/gtaonlinejobs

  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    volumes:
      - ./data/redis:/data

